//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Soft_app.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string ProductArticleNumber { get; set; }
        public int ProductNameID { get; set; }
        public int MeasureUnitID { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> MaxSizeSale { get; set; }
        public int MakerID { get; set; }
        public int SupplierID { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> Sale { get; set; }
        public Nullable<int> StoreQuantity { get; set; }
        public string Description_text { get; set; }
        public string Pages { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Maker Maker { get; set; }
        public virtual MeasureUnit MeasureUnit { get; set; }
        public virtual ProductName ProductName { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
