//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Soft_app.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_
    {
        public int id { get; set; }
        public int id_role { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string name { get; set; }
    
        public virtual role_ role_ { get; set; }
    }
}
